"""Maintenance tasks: the API the portal, the console (PM_STATUS) and the boot reminder use.

    myrhino/maintenance/tasks.json     areas, lists, status codes, the Task Library and Task Books,
                                       the tasks themselves, settings
    myrhino/maintenance/history.json   every completion / skip / status change / meter adjustment
    myrhino/maintenance/meters.json    usage meters (meters.py)
    myrhino/maintenance_status.cfg     generated: what is due, for the Mainsail prompt after a restart

All three JSON files live in the config folder, so klipper-backup keeps them. Maintenance NEVER
blocks a job: it reminds, it does not lock anything.

Words used here
    asset     what a task is for: "machine:<area>", "tool:<name>" or "hw:<system hardware name>"
    template  a task in the Task Library (no asset, no schedule state)
    book      a Task Book: a named group of templates. Assigning it to an asset adds one task per
              template there. Those tasks are LINKED: editing the template updates every one of them.
    status    the built-in states the schedule works out (overdue, due soon...) plus custom status
              codes a person sets by hand ("Pending - Waiting on parts"), each with rules.
"""
import copy
import json
import os
import re
import secrets
import threading
import time
from urllib.parse import urlparse

from .. import registry
from ..errors import Fail
from ..presets import SAFE_TEXT, SAFE_TEXT_HELP
from . import library, meters, schedule

DEFAULT_TYPES = {"inspect": "Inspect", "clean": "Clean", "lubricate": "Lubricate", "adjust": "Adjust", "replace": "Replace",
                 "calibrate": "Calibrate", "other": "Other"}
PRIORITY_IDS = ("low", "normal", "high", "critical")
DEFAULT_PRIORITIES = {"low": "Low", "normal": "Normal", "high": "High", "critical": "Critical"}
UNITS = ("days", "weeks", "months")
MAX_TASKS, MAX_RULES, MAX_LIST, MAX_HISTORY = 400, 4, 20, 3000
MAX_TEMPLATES, MAX_BOOKS, MAX_STATUSES, MAX_TYPES = 300, 60, 20, 20
AREA_ID = re.compile(r"^[a-z][a-z0-9_]{1,31}$")
COLORS = {"teal": "#26a69a", "amber": "#f9a825", "red": "#e53935", "indigo": "#5c6bc0", "purple": "#8e24aa",
          "blue": "#1e88e5", "green": "#43a047", "orange": "#fb8c00", "pink": "#d81b60", "grey": "#8d8f99"}
# Built-in statuses: worked out from the schedule (or set by the snooze / pause buttons). Their label and
# colour can change; they cannot be deleted.
BUILTIN_STATUSES = {
    "overdue": {"label": "Overdue", "color": "red", "help": "Past the due point."},
    "due_soon": {"label": "Due soon", "color": "amber", "help": "Inside the early alarm: plan the work, get the parts."},
    "ok": {"label": "Scheduled", "color": "teal", "help": "Not due yet."},
    "done": {"label": "Done", "color": "grey", "help": "A one-off task that has been done."},
    "snoozed": {"label": "Snoozed", "color": "indigo", "help": "Due, but put off for a few days."},
    "paused": {"label": "Paused", "color": "grey", "help": "Kept, but not tracked."},
}
STATUS_LISTS = {"due": "With the due tasks", "upcoming": "With the upcoming tasks", "own": "In its own group"}
STATUS_CLOCK = {"none": "Keeps running - the task still ages toward overdue",
                "pause": "Pauses - time and use while it is set do not count",
                "done": "Counts as done - the interval starts again"}
STATUS_EXPIRY = {"never": "Never - until someone changes it", "days": "After a number of days",
                 "meter": "When the machine or tool is used again"}
DEFAULT_CUSTOM_STATUSES = [
    {"id": "s_parts", "label": "Pending - Waiting on parts", "color": "purple", "list": "own", "boot_prompt": False,
     "note_required": True, "clock": "none", "expiry": "never", "expiry_days": 0, "log_option": True,
     "help": "Parts are on order. Say what in the note. The task keeps ageing so it comes back as soon as you clear it."},
    {"id": "s_progress", "label": "In progress", "color": "blue", "list": "due", "boot_prompt": True,
     "note_required": False, "clock": "none", "expiry": "days", "expiry_days": 3, "log_option": True,
     "help": "Started but not finished. Clears itself after 3 days if it is not logged."},
    {"id": "s_defer", "label": "Deferred to next shutdown", "color": "orange", "list": "upcoming", "boot_prompt": False,
     "note_required": False, "clock": "pause", "expiry": "meter", "expiry_days": 0, "log_option": True,
     "help": "Waits for a planned stop. Its clock pauses until the machine runs again."},
]
DEF_FIELDS = ("title", "type", "priority", "rules", "anchor", "first_due", "steps", "parts", "tools_needed", "minutes",
              "safety", "notes", "links", "remind_boot")
HEADER = ("# GENERATED by the Rhino portal - do not edit. It lists maintenance that was due when the portal\n"
          "# last checked; guided/maintenance.cfg shows it in a Mainsail prompt after Klipper starts.\n")


def _flag(v):
    return v in (True, 1, "1", "true", "True", "on", "yes")


def _text(v, label, maxlen, safe=True):
    s = " ".join(str(v or "").split()) if safe else str(v or "").strip()
    if len(s) > maxlen:
        raise Fail(f"{label} is too long (max {maxlen} characters)")
    if safe and not SAFE_TEXT.match(s):
        raise Fail(f"{label} may only contain {SAFE_TEXT_HELP}")
    return s


def _lines(v, label, maxlen, maxn=MAX_LIST):
    items = v.splitlines() if isinstance(v, str) else list(v or [])
    items = [str(i).strip() for i in items if str(i).strip()]
    if len(items) > maxn:
        raise Fail(f"{label}: at most {maxn} lines")
    for i in items:
        if len(i) > maxlen:
            raise Fail(f"{label}: each line at most {maxlen} characters")
    return items


def _num(v, label, lo, hi, integer=False):
    try:
        x = float(v)
    except (TypeError, ValueError):
        raise Fail(f"{label} must be a number")
    if not (lo <= x <= hi):
        raise Fail(f"{label} must be between {lo:g} and {hi:g}")
    return int(round(x)) if integer else x


def _new_id(prefix, taken):
    while True:
        i = prefix + secrets.token_hex(4)
        if i not in taken:
            return i


class MaintService:
    def __init__(self, paths, tool_service, now=time.time):
        self.paths, self.tools_svc, self.now = paths, tool_service, now
        d = os.path.join(paths.cfg, "myrhino", "maintenance")
        self.tasks_path, self.history_path = os.path.join(d, "tasks.json"), os.path.join(d, "history.json")
        self.status_cfg = os.path.join(paths.cfg, "myrhino", "maintenance_status.cfg")
        self.meters = meters.MeterStore(os.path.join(d, "meters.json"))
        self.lock = threading.RLock()
        self._tools_cache, self._tools_key = None, None
        self._boot_sig = None

    # ------------------------------------------------------------------ files
    def _fresh(self):
        return {"version": 2, "areas": copy.deepcopy(library.DEFAULT_AREAS), "tasks": {}, "settings": {"boot_reminder": True}}

    def _load_tasks(self):
        if not os.path.exists(self.tasks_path):
            d = self._fresh()
        else:
            try:
                with open(self.tasks_path, encoding="utf-8") as f:
                    d = json.load(f)
                if not isinstance(d.get("tasks"), dict):
                    raise ValueError("no tasks object")
            except (OSError, ValueError) as e:
                raise Fail(f"{self.tasks_path} is unreadable: {e}")
        d.setdefault("areas", copy.deepcopy(library.DEFAULT_AREAS))
        d.setdefault("settings", {}).setdefault("boot_reminder", True)
        d.setdefault("types", dict(DEFAULT_TYPES))
        pr = d.setdefault("priorities", dict(DEFAULT_PRIORITIES))
        for p in PRIORITY_IDS:
            pr.setdefault(p, DEFAULT_PRIORITIES[p])
        st = d.setdefault("statuses", {})
        b = st.setdefault("builtin", {})
        for k, v in BUILTIN_STATUSES.items():
            b.setdefault(k, {"label": v["label"], "color": v["color"]})
        st.setdefault("custom", copy.deepcopy(DEFAULT_CUSTOM_STATUSES))
        if "templates" not in d:                    # first run of the Task Library: seed the starter tasks
            d["templates"] = library.starter_templates()
            d["books"] = {b["id"]: {"name": b["name"], "description": b["description"], "templates": list(b["templates"]),
                                    "assigned": [], "origin": "starter", "for": b.get("for", "tool")} for b in library.STARTER_BOOKS}
        d.setdefault("books", {})
        return d

    def _load_history(self):
        if not os.path.exists(self.history_path):
            return []
        try:
            with open(self.history_path, encoding="utf-8") as f:
                return list(json.load(f).get("records", []))
        except (OSError, ValueError, AttributeError) as e:
            raise Fail(f"{self.history_path} is unreadable: {e}")

    @staticmethod
    def _atomic(path, obj):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        tmp = path + ".tmp"
        with open(tmp, "w", encoding="utf-8") as f:
            json.dump(obj, f, indent=1, sort_keys=True)
        os.replace(tmp, path)

    def _save_tasks(self, d):
        self._atomic(self.tasks_path, d)
        self.write_boot_cfg(force=True)

    def _append_history(self, rec):
        h = self._load_history()
        h.append(rec)
        self._atomic(self.history_path, {"version": 1, "records": h[-MAX_HISTORY:]})

    def _log(self, d, t, tid, action, notes="", **extra):
        self._append_history({"id": "h" + secrets.token_hex(4), "task": tid, "title": t["title"], "asset": t["asset"],
                              "asset_label": self.asset_label(t["asset"], d["areas"]), "action": action, "at": extra.pop("at", self.now()),
                              "logged": self.now(), "notes": notes, **extra})

    # ------------------------------------------------------------------ tools + hardware
    def tools(self):
        """{slot: {"name", "type", "kind_code", "builtin"}} - cached until the registry or variables change."""
        key = tuple(os.path.getmtime(p) if os.path.exists(p) else 0
                    for p in (self.paths.registry_json, self.paths.variables_cfg))
        if self._tools_cache is None or key != self._tools_key:
            reg = registry.load(self.paths)
            out = {}
            try:
                for t in self.tools_svc.list_tools():
                    out[t["slot"]] = {"name": t["name"], "type": t["type"], "builtin": t["builtin"],
                                      "kind_code": reg["tools"].get(t["name"], {}).get("kind", "")}
            except Fail:
                out = self._tools_cache or {}
            self._tools_cache, self._tools_key = out, key
        return self._tools_cache

    def tool_names(self):
        return {t["name"]: t for t in self.tools().values()}

    def hardware_names(self):
        try:
            return {n: hw for n, hw in registry.load(self.paths).get("hardware", {}).items()}
        except Fail:
            return {}

    def collector(self, moonraker):
        return meters.Collector(self.meters, moonraker, self.tools, on_change=lambda: self.write_boot_cfg())

    # ------------------------------------------------------------------ assets
    def asset_label(self, asset, areas):
        kind, _, ref = asset.partition(":")
        if kind == "tool":
            return ref
        if kind == "hw":
            return ref.replace("_", " ")
        if asset == "machine":
            return "Whole machine"
        return next((a["label"] for a in areas if a["id"] == ref), ref)

    def _check_asset(self, asset, d, allow_machine=False):
        kind, _, ref = (asset or "").partition(":")
        if allow_machine and asset == "machine":
            return asset
        if kind == "machine" and any(a["id"] == ref for a in d["areas"]):
            return asset
        if kind == "tool" and ref in self.tool_names():
            return asset
        if kind == "hw" and ref in self.hardware_names():
            return asset
        raise Fail("Choose what the task is for: a part of the machine, a tool or system hardware")

    @staticmethod
    def _tool_of(asset):
        return asset.partition(":")[2] if asset.startswith("tool:") else None

    # ------------------------------------------------------------------ status
    def _readers(self, task, frozen=None):
        tool = self._tool_of(task["asset"])

        def value(rule):
            if frozen is not None:
                k = schedule.meter_key(rule)
                if k in frozen:
                    return frozen[k]
            return self.meters.value(rule.get("scope", "machine"), rule["meter"], tool)

        def rate(rule):
            if frozen is not None:
                return None
            return self.meters.rate(rule.get("scope", "machine"), rule["meter"], tool, now=self.now())
        return value, rate

    def status_defs(self, d):
        """{id: {label, color, hex, builtin, ...rules}} for every status, built-in and custom."""
        out = {}
        for k, v in BUILTIN_STATUSES.items():
            b = d["statuses"]["builtin"].get(k, {})
            col = b.get("color", v["color"])
            out[k] = {"id": k, "label": b.get("label", v["label"]), "color": col, "hex": COLORS.get(col, COLORS["grey"]),
                      "builtin": True, "help": v["help"]}
        for c in d["statuses"]["custom"]:
            out[c["id"]] = {**c, "hex": COLORS.get(c["color"], COLORS["grey"]), "builtin": False}
        return out

    def status_of(self, task, now=None, defs=None):
        now = now or self.now()
        hold = task.get("hold")
        sdef = (defs or {}).get(hold["status"]) if hold else None
        if hold and sdef and sdef.get("clock") == "pause":         # frozen where it was when the status was set
            value, rate = self._readers(task, frozen=hold.get("meters") or {})
            st = schedule.task_status(task, hold["since"], value, rate, meters.meter_defs())
        else:
            value, rate = self._readers(task)
            st = schedule.task_status(task, now, value, rate, meters.meter_defs())
        if hold and sdef:
            st["hold"] = {"id": hold["status"], "label": sdef["label"], "hex": sdef["hex"], "list": sdef.get("list", "own"),
                          "since": hold["since"], "note": hold.get("note", ""), "clock": sdef.get("clock", "none"),
                          "boot_prompt": bool(sdef.get("boot_prompt")),
                          "until": hold["since"] + sdef.get("expiry_days", 0) * 86400 if sdef.get("expiry") == "days" else None,
                          "expiry": sdef.get("expiry", "never")}
        return st

    def _expired(self, task, sdef, now):
        hold = task["hold"]
        if sdef.get("expiry") == "days":
            return now >= hold["since"] + float(sdef.get("expiry_days") or 0) * 86400
        if sdef.get("expiry") == "meter":
            snap = self.meters.snapshot(self._tool_of(task["asset"]))
            keys = {schedule.meter_key(r) for r in task.get("rules", []) if r["kind"] == "meter"} or {"machine.prod_h"}
            return any(snap.get(k, 0) > (hold.get("meters") or {}).get(k, snap.get(k, 0)) + 0.01 for k in keys)
        return False

    def _release(self, task, sdef, now):
        """Take a custom status off a task, crediting the paused time and use if its clock was paused."""
        hold = task.pop("hold", None)
        if not hold or not sdef or sdef.get("clock") != "pause":
            return
        p = task.setdefault("paused", {"s": 0.0, "meters": {}})
        p["s"] = float(p.get("s") or 0) + max(0.0, now - hold["since"])
        snap = self.meters.snapshot(self._tool_of(task["asset"]))
        for k, v in (hold.get("meters") or {}).items():
            if k in snap:
                p["meters"][k] = float(p["meters"].get(k) or 0) + max(0.0, snap[k] - v)

    def _sweep(self, d):
        """Release custom statuses whose expiry rule has fired. Returns True if anything changed."""
        now, defs, changed = self.now(), self.status_defs(d), False
        for tid, t in d["tasks"].items():
            hold = t.get("hold")
            if not hold:
                continue
            sdef = defs.get(hold["status"])
            if sdef is None or self._expired(t, sdef, now):
                label = sdef["label"] if sdef else hold["status"]
                self._release(t, sdef, now)
                self._log(d, t, tid, "status_cleared", f"{label} ended by itself", status=label)
                changed = True
        return changed

    def overview(self):
        """Everything the maintenance screens need, in one call."""
        with self.lock:
            d = self._load_tasks()
            if self._sweep(d):
                self._atomic(self.tasks_path, d)
            now, defs = self.now(), self.status_defs(d)
            tasks = []
            for tid, t in d["tasks"].items():
                st = self.status_of(t, now, defs) if t.get("enabled", True) and not t.get("archived") else None
                tasks.append({**t, "id": tid, "asset_label": self.asset_label(t["asset"], d["areas"]), "status": st,
                              "link_info": self._link_info(d, t)})
            counts = {"overdue": 0, "due_soon": 0, "snoozed": 0, "held": 0}
            for t in tasks:
                st = t["status"]
                if not st:
                    continue
                if st.get("hold"):
                    counts["held"] += 1
                    if st["hold"]["list"] != "due":
                        continue
                if st["state"] in ("overdue", "due_soon"):
                    counts["snoozed" if st["snoozed"] else st["state"]] += 1
            return {"ok": True, "areas": d["areas"], "settings": d["settings"], "tasks": tasks, "counts": counts,
                    "meters": self.meter_report(), "types": d["types"], "priorities": {p: d["priorities"][p] for p in PRIORITY_IDS},
                    "statuses": list(defs.values()), "colors": COLORS,
                    "tools": [{"name": t["name"], "type": t["type"], "builtin": t["builtin"], "kind_code": t["kind_code"]}
                              for _, t in sorted(self.tools().items())],
                    "hardware": [{"name": n, "label": n.replace("_", " "), "category": hw.get("category", "")}
                                 for n, hw in sorted(self.hardware_names().items())],
                    "now": now}

    def _link_info(self, d, t):
        link = t.get("link")
        if not link:
            return None
        tpl = d["templates"].get(link.get("template"))
        book = d["books"].get(link.get("book") or "")
        users = sum(1 for x in d["tasks"].values() if (x.get("link") or {}).get("template") == link.get("template") and not x.get("archived"))
        return {"template": link.get("template"), "template_title": tpl["title"] if tpl else "", "book": link.get("book") or "",
                "book_name": book["name"] if book else "", "uses": users}

    def meter_report(self):
        md, now = self.meters.data, self.now()
        def rows(scope, defs, tool=None):
            return [{"meter": k, "label": v["label"], "unit": v["unit"], "help": v["help"], "event": v.get("event", ""),
                     "noun": v["noun"], "value": self.meters.value(scope, k, tool),
                     "per_day": self.meters.rate(scope, k, tool, now=now)} for k, v in defs.items()]
        names = self.tool_names()
        return {"tracking_since": md.get("tracking_since"), "imported_jobs": md.get("imported_jobs", 0),
                "machine": rows("machine", meters.MACHINE_METERS),
                "tools": {n: rows("tool", meters.TOOL_METERS, n) for n in names},
                "archived_tools": sorted(n for n in md.get("tools", {}) if n not in names),
                "adjustments": md.get("adjustments", [])[-20:]}

    # ------------------------------------------------------------------ validation
    def _clean_rule(self, r, asset):
        """asset None = a library template (a tool meter then makes it a tool-only template)."""
        kind = r.get("kind")
        if kind == "time":
            out = {"kind": "time", "every": _num(r.get("every"), "Interval", 1, 3650, integer=True),
                   "unit": r.get("unit") if r.get("unit") in UNITS else "days"}
            if r.get("lead") not in (None, ""):
                out["lead"] = _num(r["lead"], "Early alarm", 0, 3650)
                out["lead_unit"] = r.get("lead_unit") if r.get("lead_unit") in UNITS else "days"
            return out
        if kind == "date":
            try:
                schedule.day_start(str(r.get("on")))
            except (ValueError, TypeError):
                raise Fail("Choose the date for a one-off task")
            return {"kind": "date", "on": str(r["on"]), "lead": _num(r.get("lead", 7) or 0, "Early alarm", 0, 365)}
        if kind == "meter":
            scope = "tool" if r.get("scope") == "tool" else "machine"
            defs = meters.TOOL_METERS if scope == "tool" else meters.MACHINE_METERS
            if r.get("meter") not in defs:
                raise Fail("Choose what the task counts")
            if scope == "tool" and asset is not None and not asset.startswith("tool:"):
                raise Fail("A tool meter needs the task to belong to a tool")
            if _flag(r.get("event")):
                if not defs[r["meter"]].get("event"):
                    raise Fail("That meter is not an event")
                return {"kind": "meter", "meter": r["meter"], "scope": scope, "every": 1, "lead": 0, "event": True}
            out = {"kind": "meter", "meter": r["meter"], "scope": scope,
                   "every": _num(r.get("every"), "Interval", 0.1, 1e6)}
            if r.get("lead") not in (None, ""):
                out["lead"] = _num(r["lead"], "Early alarm", 0, out["every"])
            return out
        raise Fail("Each schedule rule needs a kind: time, usage, event or date")

    def _clean_def(self, f, d, asset, old=None):
        """The definition part of a task or template (everything except what it is for and its state)."""
        t = dict(old or {})
        t["title"] = _text(f.get("title"), "Title", 80)
        if not t["title"]:
            raise Fail("Give the task a title")
        t["type"] = f.get("type") if f.get("type") in d["types"] else ("inspect" if "inspect" in d["types"] else next(iter(d["types"])))
        t["priority"] = f.get("priority") if f.get("priority") in PRIORITY_IDS else "normal"
        rules = list(f.get("rules") or [])
        if not rules:
            raise Fail("Add at least one schedule rule")
        if len(rules) > MAX_RULES:
            raise Fail(f"At most {MAX_RULES} rules per task")
        t["rules"] = [self._clean_rule(r, asset) for r in rules]
        t["anchor"] = "calendar" if f.get("anchor") == "calendar" else "completion"
        if t["anchor"] == "calendar":
            try:
                schedule.day_start(str(f.get("first_due")))
            except (TypeError, ValueError):
                raise Fail("Choose the first due date for a fixed-calendar schedule")
            t["first_due"] = str(f["first_due"])
        else:
            t.pop("first_due", None)
        t["steps"] = _lines(f.get("steps"), "Steps", 200)
        t["parts"] = _lines(f.get("parts"), "Parts", 120)
        t["tools_needed"] = _text(f.get("tools_needed"), "Tools needed", 200, safe=False)
        t["minutes"] = _num(f.get("minutes") or 0, "Time needed", 0, 1440, integer=True)
        t["safety"] = _text(f.get("safety"), "Safety notes", 500, safe=False)
        t["notes"] = _text(f.get("notes"), "Notes", 1000, safe=False)
        links = _lines(f.get("links"), "Links", 300, 5)
        for u in links:
            if urlparse(u).scheme not in ("http", "https"):
                raise Fail("Links must start with http:// or https://")
        t["links"] = links
        t["remind_boot"] = _flag(f.get("remind_boot", True))
        return t

    def _clean_task(self, f, d, old=None):
        asset = self._check_asset(f.get("asset"), d)
        t = self._clean_def(f, d, asset, old)
        t["asset"] = asset
        t["enabled"] = _flag(f.get("enabled", True))
        return t

    def _baseline(self, f, task):
        """Where counting starts for a new task: now, or 'last done on <date> at these readings'."""
        now = self.now()
        snap = self.meters.snapshot(self._tool_of(task["asset"]))
        start = {"at": now, "meters": snap}
        lb = f.get("last_done") or {}
        if lb.get("when") == "date":
            try:
                at = schedule.day_start(str(lb.get("date")))
            except (TypeError, ValueError):
                raise Fail("Choose the date it was last done")
            if at > now:
                raise Fail("The last-done date cannot be in the future")
            start["at"] = at
            for k, v in (lb.get("readings") or {}).items():
                if k in snap and v not in (None, ""):
                    start["meters"][k] = _num(v, "Reading", 0, 1e7)
        return start

    # ------------------------------------------------------------------ tasks
    def create(self, f, template=None):
        with self.lock:
            d = self._load_tasks()
            if len(d["tasks"]) >= MAX_TASKS:
                raise Fail(f"At most {MAX_TASKS} tasks")
            t = self._clean_task(f, d)
            t["created"] = self.now()
            t["start"] = self._baseline(f, t)
            t["last"] = None
            if template:
                t["template"] = template
            tid = _new_id("t", d["tasks"])
            d["tasks"][tid] = t
            self._save_tasks(d)
            return {"ok": True, "id": tid}

    def update(self, tid, f):
        """Edit a task. A task linked to the Task Library only takes its own settings here (paused or
        not); its definition is the template's - edit that, or detach the task first."""
        with self.lock:
            d = self._load_tasks()
            old = d["tasks"].get(tid)
            if old is None:
                raise Fail("No such task")
            if _flag(f.get("detach")) and old.get("link"):
                old.pop("link")
                self._save_tasks(d)
                return {"ok": True, "id": tid, "detached": True}
            if old.get("link"):
                old["enabled"] = _flag(f.get("enabled", old.get("enabled", True)))
                self._save_tasks(d)
                return {"ok": True, "id": tid, "linked": True}
            t = self._clean_task(f, d, old)
            if t["asset"] != old["asset"]:      # readings belong to the old asset; restart counting
                t["start"], t["last"] = self._baseline({}, t), None
                t.pop("paused", None)
            d["tasks"][tid] = t
            self._save_tasks(d)
            return {"ok": True, "id": tid}

    def delete(self, tid):
        with self.lock:
            d = self._load_tasks()
            if d["tasks"].pop(tid, None) is None:
                raise Fail("No such task")
            self._save_tasks(d)
            return {"ok": True}

    def _log_options(self, d):
        defs = self.status_defs(d)
        return {"done": "Done", "skipped": "Skipped - not needed this time",
                **{c["id"]: c["label"] for c in d["statuses"]["custom"] if c.get("log_option")}}, defs

    def complete(self, tid, f):
        """Log work on a task: done, skipped, or one of the custom statuses offered in the Log work list."""
        with self.lock:
            d = self._load_tasks()
            t = d["tasks"].get(tid)
            if t is None:
                raise Fail("No such task")
            options, defs = self._log_options(d)
            action = f.get("action") or "done"
            if action not in options:
                raise Fail("Choose what happened")
            if action not in ("done", "skipped"):
                return self._set_status(d, tid, t, action, f.get("notes"), via_log=True)
            now = self.now()
            at = now
            if f.get("date"):
                try:
                    at = schedule.day_start(str(f["date"]))
                    if str(f["date"]) == time.strftime("%Y-%m-%d", time.localtime(now)):
                        at = now
                except (TypeError, ValueError):
                    raise Fail("Bad date")
                if at > now + 60:
                    raise Fail("The date cannot be in the future")
            snap = self.meters.snapshot(self._tool_of(t["asset"]))
            status = self.status_of(t, now, defs)
            if t.get("hold"):
                self._release(t, defs.get(t["hold"]["status"]), now)
            t["last"] = {"at": at, "meters": snap, "action": action}
            t.pop("snooze_until", None)
            t.pop("paused", None)
            self._save_tasks(d)
            self._log(d, t, tid, action, _text(f.get("notes"), "Notes", 1000, safe=False), at=at,
                      was=status["state"], readings=snap, status=(status.get("hold") or {}).get("label", ""))
            return {"ok": True}

    def set_status(self, tid, f):
        """Set (or clear, with status "") a custom status by hand."""
        with self.lock:
            d = self._load_tasks()
            t = d["tasks"].get(tid)
            if t is None:
                raise Fail("No such task")
            return self._set_status(d, tid, t, f.get("status") or "", f.get("note"))

    def _set_status(self, d, tid, t, sid, note, via_log=False):
        defs, now = self.status_defs(d), self.now()
        note = _text(note, "Note", 300, safe=False)
        if not sid:
            if not t.get("hold"):
                return {"ok": True}
            label = defs.get(t["hold"]["status"], {}).get("label", t["hold"]["status"])
            self._release(t, defs.get(t["hold"]["status"]), now)
            self._save_tasks(d)
            self._log(d, t, tid, "status_cleared", note, status=label)
            return {"ok": True}
        sdef = defs.get(sid)
        if sdef is None or sdef["builtin"]:
            raise Fail("Choose one of your status codes")
        if sdef.get("note_required") and not note:
            raise Fail(f"'{sdef['label']}' needs a note - say why (which parts, who, when)")
        before = self.status_of(t, now, defs)
        if t.get("hold"):
            self._release(t, defs.get(t["hold"]["status"]), now)
        snap = self.meters.snapshot(self._tool_of(t["asset"]))
        if sdef.get("clock") == "done":                     # counts as done: the interval starts again
            t["last"] = {"at": now, "meters": snap, "action": sid}
            t.pop("paused", None)
        t.pop("snooze_until", None)
        t["hold"] = {"status": sid, "since": now, "note": note, "meters": snap}
        self._save_tasks(d)
        self._log(d, t, tid, "status", note, status=sdef["label"], was=before["state"], readings=snap)
        return {"ok": True}

    def snooze(self, tid, days):
        with self.lock:
            d = self._load_tasks()
            t = d["tasks"].get(tid)
            if t is None:
                raise Fail("No such task")
            days = _num(days, "Snooze", 0, 90)
            if days:
                t["snooze_until"] = self.now() + days * 86400
            else:
                t.pop("snooze_until", None)
            self._save_tasks(d)
            return {"ok": True}

    # ------------------------------------------------------------------ admin lists
    def save_areas(self, areas):
        with self.lock:
            d = self._load_tasks()
            clean, seen = [], set()
            for a in areas or []:
                label = _text(a.get("label"), "Area name", 40)
                aid = (a.get("id") or re.sub(r"[^a-z0-9_]+", "_", label.lower()).strip("_")[:32] or "area")
                if not AREA_ID.match(aid) or aid in seen:
                    aid = f"area_{secrets.token_hex(3)}"
                if label:
                    clean.append({"id": aid, "label": label})
                    seen.add(aid)
            used = {t["asset"].partition(":")[2] for t in d["tasks"].values() if t["asset"].startswith("machine:") and not t.get("archived")}
            missing = used - seen
            if missing:
                raise Fail("These areas still have tasks: " + ", ".join(sorted(missing)) + ". Move or delete the tasks first.")
            if not clean:
                raise Fail("Keep at least one area")
            d["areas"] = clean
            self._save_tasks(d)
            return {"ok": True, "areas": clean}

    def save_lists(self, f):
        """Kinds of work (add / rename / remove unused) and priority names (rename only)."""
        with self.lock:
            d = self._load_tasks()
            if "types" in f:
                types, seen = {}, set()
                for raw in f["types"] or []:
                    label = _text(raw.get("label"), "Kind of work", 30)
                    if not label:
                        continue
                    tid = raw.get("id") or re.sub(r"[^a-z0-9_]+", "_", label.lower()).strip("_")[:24] or "work"
                    if not AREA_ID.match(tid) or tid in seen:
                        tid = f"work_{secrets.token_hex(2)}"
                    seen.add(tid)
                    types[tid] = label
                if not types:
                    raise Fail("Keep at least one kind of work")
                if len(types) > MAX_TYPES:
                    raise Fail(f"At most {MAX_TYPES} kinds of work")
                used = {t.get("type") for t in list(d["tasks"].values()) + list(d["templates"].values())}
                gone = [d["types"][k] for k in d["types"] if k not in types and k in used]
                if gone:
                    raise Fail(f"Tasks still use {', '.join(gone)} - change them first, or rename it instead")
                d["types"] = types
            if "priorities" in f:
                for p in PRIORITY_IDS:
                    label = _text((f["priorities"] or {}).get(p), "Priority name", 20)
                    if label:
                        d["priorities"][p] = label
            self._save_tasks(d)
            return {"ok": True, "types": d["types"], "priorities": d["priorities"]}

    def save_statuses(self, f):
        """Built-in statuses: label and colour. Custom ones: everything, plus add / delete."""
        with self.lock:
            d = self._load_tasks()
            for k, v in (f.get("builtin") or {}).items():
                if k not in BUILTIN_STATUSES:
                    continue
                label = _text(v.get("label"), "Status name", 30) or BUILTIN_STATUSES[k]["label"]
                d["statuses"]["builtin"][k] = {"label": label, "color": v.get("color") if v.get("color") in COLORS else BUILTIN_STATUSES[k]["color"]}
            if "custom" in f:
                out, seen = [], set()
                labels = {v["label"].lower() for v in d["statuses"]["builtin"].values()}
                for raw in f["custom"] or []:
                    label = _text(raw.get("label"), "Status name", 40)
                    if not label:
                        raise Fail("Every status code needs a name")
                    if label.lower() in labels or label.lower() in {x["label"].lower() for x in out}:
                        raise Fail(f"There is already a status called {label}")
                    sid = raw.get("id") if re.match(r"^s_[a-z0-9_]{1,30}$", str(raw.get("id") or "")) else _new_id("s_", seen)
                    if sid in seen:
                        sid = _new_id("s_", seen)
                    seen.add(sid)
                    exp = raw.get("expiry") if raw.get("expiry") in STATUS_EXPIRY else "never"
                    s = {"id": sid, "label": label, "color": raw.get("color") if raw.get("color") in COLORS else "purple",
                         "help": _text(raw.get("help"), f"{label} description", 200, safe=False),
                         "list": raw.get("list") if raw.get("list") in STATUS_LISTS else "own",
                         "boot_prompt": _flag(raw.get("boot_prompt")), "note_required": _flag(raw.get("note_required")),
                         "clock": raw.get("clock") if raw.get("clock") in STATUS_CLOCK else "none",
                         "expiry": exp, "expiry_days": _num(raw.get("expiry_days") or 0, f"{label} days", 0, 365, integer=True) if exp == "days" else 0,
                         "log_option": _flag(raw.get("log_option"))}
                    if exp == "days" and s["expiry_days"] < 1:
                        raise Fail(f"{label}: give the number of days before it ends by itself")
                    out.append(s)
                if len(out) > MAX_STATUSES:
                    raise Fail(f"At most {MAX_STATUSES} status codes")
                in_use = {t["hold"]["status"] for t in d["tasks"].values() if t.get("hold")}
                gone = [c["label"] for c in d["statuses"]["custom"] if c["id"] not in seen and c["id"] in in_use]
                if gone:
                    raise Fail(f"Tasks are set to {', '.join(gone)} - clear them first")
                d["statuses"]["custom"] = out
            self._save_tasks(d)
            return {"ok": True, "statuses": list(self.status_defs(d).values())}

    def lists_view(self):
        d = self._load_tasks()
        used_types = {}
        for t in list(d["tasks"].values()) + list(d["templates"].values()):
            used_types[t.get("type")] = used_types.get(t.get("type"), 0) + 1
        in_use = {}
        for t in d["tasks"].values():
            if t.get("hold"):
                in_use[t["hold"]["status"]] = in_use.get(t["hold"]["status"], 0) + 1
        return {"ok": True, "types": d["types"], "type_use": used_types, "priorities": {p: d["priorities"][p] for p in PRIORITY_IDS},
                "areas": d["areas"], "statuses": {"builtin": {k: d["statuses"]["builtin"][k] for k in BUILTIN_STATUSES},
                                                 "custom": d["statuses"]["custom"]}, "builtin_status_help": {k: v["help"] for k, v in BUILTIN_STATUSES.items()},
                "status_use": in_use, "colors": COLORS, "status_lists": STATUS_LISTS, "status_clock": STATUS_CLOCK,
                "status_expiry": STATUS_EXPIRY}

    def save_settings(self, f):
        with self.lock:
            d = self._load_tasks()
            if "boot_reminder" in f:
                d["settings"]["boot_reminder"] = _flag(f["boot_reminder"])
            self._save_tasks(d)
            return {"ok": True, "settings": d["settings"]}

    def adjust_meter(self, f):
        scope = "tool" if f.get("scope") == "tool" else "machine"
        tool = f.get("tool") if scope == "tool" else None
        if tool and tool not in self.tool_names() and tool not in self.meters.data.get("tools", {}):
            raise Fail("No such tool")
        note = _text(f.get("note"), "Note", 200, safe=False)
        old = self.meters.adjust(scope, f.get("meter"), f.get("value"), tool, note, self.now())
        defs = meters.MACHINE_METERS if scope == "machine" else meters.TOOL_METERS
        self._append_history({"id": "h" + secrets.token_hex(4), "task": "", "title": f"Meter set: {defs[f['meter']]['label']}",
                              "asset": f"tool:{tool}" if tool else "machine:", "asset_label": tool or "Machine",
                              "action": "meter", "at": self.now(), "logged": self.now(), "notes": note,
                              "from": old, "to": float(f.get("value"))})
        self.write_boot_cfg(force=True)
        return {"ok": True}

    # ------------------------------------------------------------------ Task Library + Task Books
    @staticmethod
    def _applies(tpl):
        return "tool" if any(r.get("scope") == "tool" for r in tpl.get("rules", []) if r["kind"] == "meter") else "any"

    def library(self):
        """The Task Library: templates (with how many tasks use each) and Task Books."""
        with self.lock:
            d = self._load_tasks()
        defs = meters.meter_defs()
        uses = {}
        for t in d["tasks"].values():
            k = (t.get("link") or {}).get("template")
            if k and not t.get("archived"):
                uses.setdefault(k, []).append(self.asset_label(t["asset"], d["areas"]))
        tpls = []
        for k, t in d["templates"].items():
            tpls.append({**t, "id": k, "applies": self._applies(t), "uses": sorted(uses.get(k, [])),
                         "schedule": " or ".join(schedule.describe(r, defs) for r in t["rules"]),
                         "books": [b["name"] for b in d["books"].values() if k in b["templates"]],
                         "area_label": self.asset_label("machine:" + t["area"], d["areas"]) if t.get("area") else ""})
        tpls.sort(key=lambda x: (x["applies"] != "any", x["title"].lower()))
        books = []
        for k, b in d["books"].items():
            books.append({**b, "id": k, "assigned_labels": [self.asset_label(a, d["areas"]) for a in b["assigned"]],
                          "needs_tool": any(self._applies(d["templates"][x]) == "tool" for x in b["templates"] if x in d["templates"])})
        books.sort(key=lambda x: (x.get("origin") == "starter", x["name"].lower()))
        sugg = {t["name"]: library.suggested_book(t) for t in self.tools().values()}
        return {"ok": True, "templates": tpls, "books": books, "areas": d["areas"], "types": d["types"],
                "priorities": {p: d["priorities"][p] for p in PRIORITY_IDS}, "suggested": sugg}

    def template_save(self, tid, f):
        """Create (tid None) or edit a library task. Editing updates every task linked to it."""
        with self.lock:
            d = self._load_tasks()
            old = d["templates"].get(tid) if tid else None
            if tid and old is None:
                raise Fail("No such library task")
            if not tid and len(d["templates"]) >= MAX_TEMPLATES:
                raise Fail(f"At most {MAX_TEMPLATES} library tasks")
            t = self._clean_def(f, d, None, old)
            area = f.get("area") or (old or {}).get("area") or ""
            t["area"] = area if any(a["id"] == area for a in d["areas"]) else ""
            t.setdefault("origin", "user")
            if old:
                for x in d["tasks"].values():           # a tool-only template cannot stay on a machine task
                    if (x.get("link") or {}).get("template") == tid and not x.get("archived") and \
                            self._applies(t) == "tool" and not x["asset"].startswith("tool:"):
                        raise Fail(f"{x['title']} on {self.asset_label(x['asset'], d['areas'])} uses this task, and a tool meter "
                                   f"only works on a tool. Remove that task from the machine first.")
            tid = tid or _new_id("u_", d["templates"])
            d["templates"][tid] = t
            n = self._sync_template(d, tid)
            self._save_tasks(d)
            return {"ok": True, "id": tid, "updated_tasks": n}

    def _sync_template(self, d, tid):
        """Copy a template's definition into every task linked to it. Schedule state is kept."""
        tpl, n = d["templates"][tid], 0
        for t in d["tasks"].values():
            if (t.get("link") or {}).get("template") == tid:
                for k in DEF_FIELDS:
                    if k in tpl:
                        t[k] = copy.deepcopy(tpl[k])
                    else:
                        t.pop(k, None)
                n += 1
        return n

    def template_delete(self, tid):
        """Delete a library task. Tasks made from it are kept as ordinary (unlinked) tasks."""
        with self.lock:
            d = self._load_tasks()
            if d["templates"].pop(tid, None) is None:
                raise Fail("No such library task")
            kept = 0
            for t in d["tasks"].values():
                if (t.get("link") or {}).get("template") == tid:
                    t.pop("link")
                    kept += 1
            for b in d["books"].values():
                b["templates"] = [x for x in b["templates"] if x != tid]
            self._save_tasks(d)
            return {"ok": True, "detached": kept}

    def template_from_task(self, task_id):
        """Turn an ordinary task into a library task and link the task to it."""
        with self.lock:
            d = self._load_tasks()
            t = d["tasks"].get(task_id)
            if t is None:
                raise Fail("No such task")
            if t.get("link"):
                raise Fail("This task already comes from the Task Library")
            tpl = {k: copy.deepcopy(t[k]) for k in DEF_FIELDS if k in t}
            tpl.update(origin="user", area=t["asset"].partition(":")[2] if t["asset"].startswith("machine:") else "")
            tid = _new_id("u_", d["templates"])
            d["templates"][tid] = tpl
            t["link"] = {"template": tid, "book": ""}
            self._save_tasks(d)
            return {"ok": True, "id": tid}

    def _targets(self, d, asset, tpl):
        """Where a template lands when assigned to `asset` ("machine" = each template's own area)."""
        if asset == "machine":
            if self._applies(tpl) == "tool":
                return None
            area = tpl.get("area") if any(a["id"] == tpl.get("area") for a in d["areas"]) else d["areas"][-1]["id"]
            return f"machine:{area}"
        if self._applies(tpl) == "tool" and not asset.startswith("tool:"):
            return None
        return asset

    def _add_linked(self, d, tid, asset, book_id):
        """One linked task for template tid on asset (revives an archived one). Returns 'added'/'kept'/None."""
        tpl = d["templates"][tid]
        for x in d["tasks"].values():
            if (x.get("link") or {}).get("template") == tid and x["asset"] == asset:
                if x.get("archived"):
                    x.pop("archived", None)
                    x["enabled"] = True
                    x["link"]["book"] = book_id
                    return "added"
                return "kept"
        if len(d["tasks"]) >= MAX_TASKS:
            raise Fail(f"At most {MAX_TASKS} tasks")
        t = {k: copy.deepcopy(tpl[k]) for k in DEF_FIELDS if k in tpl}
        t.update(asset=asset, enabled=True, created=self.now(), last=None, link={"template": tid, "book": book_id})
        t["start"] = self._baseline({}, t)
        d["tasks"][_new_id("t", d["tasks"])] = t
        return "added"

    def assign_template(self, tid, asset):
        """Add one library task to an asset (linked)."""
        with self.lock:
            d = self._load_tasks()
            if tid not in d["templates"]:
                raise Fail("No such library task")
            self._check_asset(asset, d, allow_machine=True)
            where = self._targets(d, asset, d["templates"][tid])
            if where is None:
                raise Fail(f"{d['templates'][tid]['title']} counts a tool's own use, so it can only go on a toolhead")
            r = self._add_linked(d, tid, where, "")
            self._save_tasks(d)
            return {"ok": True, "added": 1 if r == "added" else 0}

    def book_save(self, bid, f):
        """Create or edit a Task Book. Assets it is assigned to gain new tasks; removed ones are archived."""
        with self.lock:
            d = self._load_tasks()
            old = d["books"].get(bid) if bid else None
            if bid and old is None:
                raise Fail("No such Task Book")
            if not bid and len(d["books"]) >= MAX_BOOKS:
                raise Fail(f"At most {MAX_BOOKS} Task Books")
            name = _text(f.get("name"), "Book name", 60)
            if not name:
                raise Fail("Give the Task Book a name")
            if name.lower() in {b["name"].lower() for k, b in d["books"].items() if k != bid}:
                raise Fail(f"There is already a Task Book called {name}")
            tpls = []
            for x in f.get("templates") or []:
                if x not in d["templates"]:
                    raise Fail("A task in the book is not in the Task Library")
                if x not in tpls:
                    tpls.append(x)
            if not tpls:
                raise Fail("Put at least one library task in the book")
            b = dict(old or {"assigned": [], "origin": "user"})
            b.update(name=name, description=_text(f.get("description"), "Description", 200, safe=False), templates=tpls)
            for a in b["assigned"]:
                bad = [d["templates"][x]["title"] for x in tpls if self._targets(d, a, d["templates"][x]) is None]
                if bad:
                    raise Fail(f"The book is on {self.asset_label(a, d['areas'])}, but {', '.join(bad)} only work on a toolhead")
            bid = bid or _new_id("b_", d["books"])
            removed = [x for x in (old or {}).get("templates", []) if x not in tpls]
            d["books"][bid] = b
            added = 0
            for a in b["assigned"]:
                for x in tpls:
                    added += self._add_linked(d, x, self._targets(d, a, d["templates"][x]), bid) == "added"
                for x in removed:
                    self._archive_linked(d, bid, a, x)
            self._save_tasks(d)
            return {"ok": True, "id": bid, "added": added}

    def _archive_linked(self, d, bid, asset, tid):
        """Archive the task book `bid` gave `asset` for template tid - unless another assigned book has it too."""
        for t in d["tasks"].values():
            link = t.get("link") or {}
            if link.get("template") != tid or link.get("book") != bid or t.get("archived"):
                continue
            if asset == "machine" and not t["asset"].startswith("machine:") or asset != "machine" and t["asset"] != asset:
                continue
            other = next((k for k, ob in d["books"].items() if k != bid and tid in ob["templates"] and asset in ob["assigned"]), None)
            if other:
                link["book"] = other
            else:
                t["archived"], t["enabled"] = True, False

    def book_delete(self, bid):
        with self.lock:
            d = self._load_tasks()
            b = d["books"].get(bid)
            if b is None:
                raise Fail("No such Task Book")
            for a in list(b["assigned"]):
                for x in b["templates"]:
                    self._archive_linked(d, bid, a, x)
            del d["books"][bid]
            self._save_tasks(d)
            return {"ok": True}

    def book_assign(self, bid, asset, on=True):
        """Assign a Task Book to an asset (adds its tasks, linked) or take it off (archives them)."""
        with self.lock:
            d = self._load_tasks()
            b = d["books"].get(bid)
            if b is None:
                raise Fail("No such Task Book")
            self._check_asset(asset, d, allow_machine=True)
            if on:
                bad = [d["templates"][x]["title"] for x in b["templates"] if self._targets(d, asset, d["templates"][x]) is None]
                if bad:
                    raise Fail(f"{b['name']} has tasks that count a tool's own use ({', '.join(bad[:3])}), so it can only go on a toolhead")
                if asset not in b["assigned"]:
                    b["assigned"].append(asset)
                added = sum(self._add_linked(d, x, self._targets(d, asset, d["templates"][x]), bid) == "added" for x in b["templates"])
                self._save_tasks(d)
                return {"ok": True, "added": added}
            if asset in b["assigned"]:
                b["assigned"].remove(asset)
                for x in b["templates"]:
                    self._archive_linked(d, bid, asset, x)
            self._save_tasks(d)
            return {"ok": True}

    # ------------------------------------------------------------------ legacy starter picker (CLI + tests)
    def library_view(self):
        d = self._load_tasks()
        have = {(t.get("template"), t["asset"]) for t in d["tasks"].values()}
        have |= {((t.get("link") or {}).get("template"), t["asset"]) for t in d["tasks"].values() if not t.get("archived")}
        defs = meters.meter_defs()
        def entry(tpl, key, asset):
            return {"key": key, "asset": asset, "asset_label": self.asset_label(asset, d["areas"]), "title": tpl["title"],
                    "type": tpl["type"], "schedule": " or ".join(schedule.describe(r, defs) for r in tpl["rules"]) + ", whichever comes first"
                    if len(tpl["rules"]) > 1 else schedule.describe(tpl["rules"][0], defs),
                    "added": (key, asset) in have}
        out = []
        areas = {a["id"] for a in d["areas"]}
        for tpl in library.MACHINE:
            area = tpl["area"] if tpl["area"] in areas else d["areas"][-1]["id"]
            out.append(entry(tpl, f"machine:{tpl['id']}", f"machine:{area}"))
        for _, tool in sorted(self.tools().items()):
            for tpl in library.for_tool(tool):
                out.append(entry(tpl, f"tool:{tpl['id']}", f"tool:{tool['name']}"))
        return {"ok": True, "templates": out}

    def library_add(self, picks):
        """Add starter tasks as ordinary tasks. All picks are checked first, so a bad one adds nothing."""
        tpls, added = library.by_id(), []
        d = self._load_tasks()
        for p in picks or []:
            if p.get("key") not in tpls:
                raise Fail("Unknown starter task")
            self._check_asset(p.get("asset"), d)
        for p in picks or []:
            tpl = tpls.get(p.get("key"))
            f = {"title": tpl["title"], "asset": p.get("asset"), "type": tpl["type"], "priority": tpl.get("priority", "normal"),
                 "rules": copy.deepcopy(tpl["rules"]), "steps": tpl.get("steps", []), "parts": tpl.get("parts", []),
                 "minutes": tpl.get("minutes", 0), "safety": tpl.get("safety", "")}
            added.append(self.create(f, template=p["key"])["id"])
        return {"ok": True, "added": len(added)}

    # ------------------------------------------------------------------ registry hooks
    def asset_renamed(self, old, new):
        with self.lock:
            d = self._load_tasks()
            for t in d["tasks"].values():
                if t["asset"] == old:
                    t["asset"] = new
            for b in d["books"].values():
                b["assigned"] = [new if a == old else a for a in b["assigned"]]
            self._tools_cache = None
            self._atomic(self.tasks_path, d)
            self.write_boot_cfg(force=True)

    def asset_removed(self, asset):
        """Keep the history; archive the asset's tasks so they stop reminding, and unassign its books."""
        with self.lock:
            d = self._load_tasks()
            for t in d["tasks"].values():
                if t["asset"] == asset:
                    t["archived"], t["enabled"] = True, False
            for b in d["books"].values():
                b["assigned"] = [a for a in b["assigned"] if a != asset]
            self._tools_cache = None
            self._atomic(self.tasks_path, d)
            self.write_boot_cfg(force=True)

    def tool_renamed(self, old, new):
        self.asset_renamed(f"tool:{old}", f"tool:{new}")
        self.meters.rename_tool(old, new)

    def tool_removed(self, name):
        self.asset_removed(f"tool:{name}")

    # ------------------------------------------------------------------ console + boot reminder
    def due_items(self):
        """[(state, asset label, title, detail, remind, priority rank)] most urgent first, for reminders.
        Snoozed tasks are left out; so are tasks with a custom status that does not keep the reminder."""
        ov = self.overview()
        items = []
        for t in ov["tasks"]:
            st = t["status"]
            if not st or st["snoozed"] or st["state"] not in ("overdue", "due_soon"):
                continue
            hold = st.get("hold")
            if hold and not hold["boot_prompt"]:
                continue
            detail = _due_point(st["next"]) + (f" - {hold['label']}" if hold else "")
            items.append((st["state"], t["asset_label"], t["title"], detail, t.get("remind_boot", True),
                          {"low": 3, "normal": 2, "high": 1, "critical": 0}[t.get("priority", "normal")]))
        items.sort(key=lambda x: (x[0] != "overdue", x[5], x[1], x[2]))
        return items, ov

    def console_lines(self):
        items, ov = self.due_items()
        if not items:
            return ["Maintenance: nothing is due."]
        out = [f"Maintenance: {ov['counts']['overdue']} overdue, {ov['counts']['due_soon']} due soon"
               + (f", {ov['counts']['snoozed']} snoozed" if ov["counts"]["snoozed"] else "")]
        for st, asset, title, detail, *_ in items:
            out.append(f"{'OVERDUE ' if st == 'overdue' else 'due soon'} {asset}: {title} ({detail})")
        return out

    def write_boot_cfg(self, force=False):
        """Rewrite maintenance_status.cfg when the list of due tasks changes (Klipper reads it at startup)."""
        try:
            items, ov = self.due_items()
        except Fail:
            return
        rows = [[st, _safe(asset), _safe(title), _safe(detail)] for st, asset, title, detail, remind, _ in items if remind]
        enabled = 1 if ov["settings"].get("boot_reminder", True) else 0
        sig = (tuple(map(tuple, rows)), enabled)
        if sig == self._boot_sig and not force and os.path.exists(self.status_cfg):
            return
        self._boot_sig = sig
        text = (HEADER + "[gcode_macro _PM_STATE]\n"
                "description: Maintenance due when the portal last checked (generated - do not edit)\n"
                f"variable_due_list: {registry.pyrepr(rows)}\n"
                f"variable_enabled: {enabled}\n"
                f"variable_written: {registry.pyrepr(time.strftime('%d %b %Y %H:%M', time.localtime(self.now())))}\n"
                "variable_shown: 0\n"
                "gcode:\n  {% if false %}{% endif %}\n")
        tmp = self.status_cfg + ".tmp"
        with open(tmp, "w", encoding="utf-8") as f:
            f.write(text)
        os.replace(tmp, self.status_cfg)


def _due_point(r):
    """Stable words for when it is/was due ('due at 200 h', 'due 15 Jan 2027') - no counters that tick."""
    if not r:
        return ""
    if r.get("event"):
        return r.get("summary", "")
    if r.get("due_value") is not None:
        return "due at " + schedule.fmt_amount(r["due_value"], r.get("unit", ""), r.get("noun", ""))
    if r.get("due_ts"):
        return "due " + schedule.fmt_date(r["due_ts"])
    return r.get("summary", "")


def _safe(s):
    """Klipper prompt text: keep only characters that are safe inside RESPOND MSG="..."."""
    s = re.sub(r"[^A-Za-z0-9 _.,:!?()/+-]", "", str(s))
    return s[:90]
