"""Content transcribed from Mike's Rhino Manual (9-18-26), lightly copy-edited (typos fixed)."""

MICROCONTROLLER = ["Capable of running Klipper firmware", "1 × 24 V hotend PWM channel",
                   "1 channel capable of controlling a 5 V servo", "7 × 24 V PWM channels", "3 × 24 V on/off channels",
                   "3–5 thermistor input channels", "6–8 individual stepper outputs", "1 RGB LED channel", "3 endstop inputs"]
MAINBOARD = ["Capable of running Klipper firmware", "2 USB channels"]
HARDWARE = [("3", "DIN-mount SSR rated 3–30 V / 220 V"), ("3", "DIN-mount 24 V / 24 V SSR"), ("1", "21W4 female socket connector"),
            ("1", "40 mm double-stack Delta fan"), ("1", "40 mm fan"), ("2", "DIN-mount 20 A circuit breaker, 12–120 V"),
            ("1", "DIN-mount CP40-1P 275 V surge protection"), ("1", "DIN-mount DZ47-63 3P breaker"), ("24", "211B terminal block"),
            ("50", "Fusable-style terminal block"), ("4", "DIN-mount UK10-DREHSI connector"), ("6", "300 mm DIN rail"),
            ("3", "Solid-state relay heatsinks"), ("1", "WJ175 JQX-38F high-current relay"), ("3", "12 V white LED strips"),
            ("1", "12 V RGB LED strip"), ("1", "12 V power supply"), ("1", "24 V power supply"), ("1", "T12 leadscrew"),
            ("2", "T8 leadscrew with the same lead as the T12"), ("4", "20T 15 mm belt 2GT pulleys (5 mm bore)"),
            ("12", "608zz ABEC-7 bearing"), ("4", "12 mm bearings"), ("16", "15 mm idler pulleys"),
            ("6", "5 mm × 120 mm stainless steel toy shafts"), ("2", "8 mm × 200 mm stainless steel toy shafts"),
            ("4", "M/F 8 mm × 20 mm camera rosette"), ("1", "110 V fused power plug"), ("1", "220 V power plug"),
            ("6–8", "NEMA 17 stepper motors"), ("3", "Optical endstops"), ("1", "8 ft CPAP hose"), ("1", "PC817 12 V optocoupler")]

# Umbilical pin -> (board pin, function, board label)
UMBILICAL = {1: ("PA2 +", "Hotend heater", "HE0"), 2: ("–", "Hotend heater", ""), 3: ("PF4 –", "Hotend thermistor", "T0"),
             4: ("+", "Hotend thermistor", ""), 5: ("PE5", "Hotend fan", "Fan0"), 6: ("–", "Hotend fan", ""),
             7: ("A1", "Stepper A1", "Motor2"), 8: ("A2", "Stepper A2", ""), 9: ("B1", "Stepper B1", ""), 10: ("B2", "Stepper B2", ""),
             11: ("PA1 +", "24 V power activate", "Bed Out"), 12: ("–", "24 V power activate", ""), 13: ("–", "Probe", "Probe"),
             14: ("+", "Probe", ""), 15: ("PG10", "Probe signal", ""), 16: ("PB0", "Laser PWM (5 V required)", "RGB"),
             17: ("", "", ""), 18: ("PB11", "PWM signal 24 V –, ESC signal to GND pin", ""), 19: ("", "", ""),
             20: ("PD12 +", "12 V power activate +", "Fan2"), 21: ("–", "12 V power activate –", "")}
CONSTANT = [("X-limit switch", "PG6"), ("Chamber temperature", "PF5"), ("Umbilical LED", "PD14")]
OTHER_PINS = [("PA8", "Part cooling fan PWM", "Fan5", "Power provided through an always-on port of the Octopus board"),
              ("", "Driver cooling fan PWM", "", "Power provided through an always-on port of the Octopus board"),
              ("PA3", "Bed 0 power", "HE1", ""), ("PD14", "Umbilical LED", "Fan4", ""), ("PF3", "Bed temperature", "TB", ""),
              ("PF5", "Chamber temperature", "T1", ""), ("PG6", "X limit", "", ""), ("PG9", "Y limit", "", ""), ("", "Z max", "", "")]

STEPPERS = [  # axis, driver, run current, socket, step, dir, enable, cs/uart, note
    ("X", "BTT TMC2240", "1.1 A", "0", "PF13", "PF12", "PF14", "PC4", ""),
    ("Y", "BTT TMC2240", "1.1 A", "1", "PG0", "PG1", "PF15", "PD11", ""),
    ("E<sub>0</sub>", "BTT TMC2240", "0.8 A", "4", "PF9", "PF10", "PG2", "PF2", "Pins and current from printer.cfg [extruder]"),
    ("Z<sub>0</sub>", "BTT TMC2208 v3.0", "0.65 A", "5", "PE6", "PA14", "PE0", "PD3", ""),
    ("Z<sub>1</sub>", "BTT TMC2208 v3.0", "0.8 A", "6", "PC13", "PF0", "PF1", "PE4", ""),
    ("Z<sub>2</sub>", "BTT TMC2208 v3.0", "0.8 A", "7", "PE2", "PE3", "PD4", "PE1", ""),
    ("X<sub>1</sub>", "BTT TMC2240", "0.8 A", "", "", "", "", "", ""),
    ("Y<sub>1</sub>", "BTT TMC2240", "0.8 A", "", "", "", "", "", ""),
    ("", "", "", "", "", "", "", "", ""),
    ("", "", "", "", "", "", "", "", ""),
]

TOOLS = {
    "BlockOne": {
        "slot": 1, "function": "3D printing (0.4 and 0.8 mm nozzles)",
        "about": "Direct-drive 3D printing, with profiles for 0.4 mm and 0.8 mm nozzles in OrcaSlicer. E3D v6 Volcano hotend at 24 V, BMG drive gear and 1.75 mm filament.",
        "setup": "Slicer start G-code (<code>START_JOB</code>)", "outputs": "Hotend heater, hotend fan, part-cooling fan",
        "pins": {1: "24 V hotend", 2: "24 V hotend", 3: "Thermistor", 4: "Thermistor", 5: "24 V hotend fan", 6: "24 V hotend fan",
                 7: "Stepper", 8: "Stepper", 9: "Stepper", 10: "Stepper", 13: "Probe", 14: "Probe", 15: "Probe"},
        "image": "tool_blockone", "image_notes": ["Part cooling provided by the universal blow-air system."],
        "printed": [("1", "BlockOne Rhino Mount"), ("1", "BlockOne Engine"), ("1", "BlockOne Tension Arm"), ("1", "V6 Mount")],
        "hardware": [("1", "BMG big gear and shaft"), ("1", "625zz sealed bearing"), ("2", "MR185 sealed bearing"),
                     ("3", "3 × 5 × 7 brass sleeve bearing"), ("1", "24 V E3D v6 Volcano hotend assembly"),
                     ("1", "J4-HV inductive proximity sensor"), ("1", "25 mm NEMA 14 stepper motor"), ("1", "30 × 3 mm toy shaft"),
                     ("1", "4 × 8 × 25 mm medium-duty (bed) spring"), ("1", "21W4 male socket connector")],
        "fasteners": [("6", "M3 × 20 mm socket head cap bolt"), ("1", "M3 × 30 mm socket head cap bolt"), ("6", "2 × 6 × 6 mm M3 square nut"),
                      ("1", "M5 × 12 mm socket head cap bolt"), ("1", "M4 × 50 mm socket head cap bolt"), ("1", "M4 × 2 mm thumb nut"),
                      ("1", "M4 washer"), ("7", "M3 washers"), ("5", "Small zip ties"), ("1", "Medium zip tie")],
        "parts_notes": [],
    },
    "SwitchFly": {
        "slot": 2, "function": "Dual-extrusion 3D printing (0.4 and 0.8 mm nozzles)",
        "about": "Dual extrusion at its finest: the first true direct-drive, dual-extrusion, single-nozzle extruder for 3D printing. Optimized for the E3D v6 Volcano hotend and BMG drive gear, and rated at 24 V for 1.75 mm filament.",
        "setup": "Slicer start G-code (<code>START_JOB</code>)", "outputs": "Hotend heater, fans, filament-path servo (<code>SERVO_LASER</code>)",
        "pins": {1: "24 V + hotend", 2: "24 V hotend", 3: "Thermistor", 4: "Thermistor", 5: "24 V hotend fan", 6: "24 V hotend fan",
                 7: "Stepper", 8: "Stepper", 9: "Stepper", 10: "Stepper", 11: "24 V + power activate", 12: "24 V – power activate",
                 13: "Probe", 14: "Probe", 15: "Probe", 18: "PWM – signal"},
        "image": "tool_switchfly", "image_notes": ["Part cooling provided by the universal blow-air system."],
        "printed": [("1", "SwitchFly Rhino Mount"), ("1", "Cam"), ("1", "Linkage Arm"), ("1", "Left Tension Arm"), ("1", "Right Tension Arm"),
                    ("1", "SwitchFly Engine"), ("1", "V6 Mount"), ("1", "30 mm Fan Spacer")],
        "hardware": [("1", "BMG big gear and shaft"), ("2", "625zz sealed bearing"), ("2", "MR185 sealed bearing"),
                     ("8", "3 × 5 × 7 brass sleeve bearing"), ("1", "24 V E3D v6 Volcano hotend assembly"),
                     ("1", "J4-HV inductive proximity sensor"), ("5", "Small zip ties"), ("1", "Medium zip tie"),
                     ("1", "25 mm NEMA 14 stepper motor"), ("1", "Ecopower 827 12 g micro servo"), ("1", "12 mm control horn"),
                     ("1", "35 × 3 mm toy shaft"), ("2", "30 × 3 mm toy shaft"), ("1", "3 mm × 25 mm expansion spring"),
                     ("1", "21W4 male socket connector"), ("1", "3-pin servo extension cable"), ("1", "24 V 30 mm fan")],
        "fasteners": [("3", "M3 × 30 mm socket head cap bolt"), ("4", "M3 × 25 mm socket head cap bolt"), ("6", "2 × 6 × 6 mm M3 square nut"),
                      ("2", "M3 × 6 mm flat head bolt"), ("2", "M5 × 12 mm button head bolt"), ("2", "M5 square nut"),
                      ("4", "M3 × 12 mm socket head cap bolt"), ("2", "M2 × 6 mm Phillips head screw"), ("7", "M3 washers")],
        "parts_notes": ["Shaft rotation is negated by the custom G0 and G1 Klipper commands.",
                        "Ensure the servo default angle is set to 90 degrees in Klipper."],
    },
    "LightSaber": {
        "slot": 3, "function": "Laser cutting and engraving",
        "about": "12 V, 80 W, 450 nm blue diode laser cutter and engraver.",
        "setup": "<code>LASER_JOB_SETUP FILE=&lt;name&gt;.gcode</code>", "outputs": "<code>LASER_INITIALIZE</code> 12 V rail, <code>SERVO_LASER</code> intensity",
        "pins": {3: "Thermistor", 4: "Thermistor", 13: "Probe", 14: "Probe", 15: "Probe", 16: "Laser PWM (5 V)",
                 20: "+ 12 V power activate", 21: "– 12 V power activate"},
        "image": "tool_lightsaber", "image_notes": ["Blow-air provided by the universal blow-air system."],
        "printed": [("1", "Light Saber Rhino Mount"), ("1", "Laser Module Bracket"), ("1", "Sensor Clamp Arm")],
        "hardware": [("1", "80 W blue diode laser"), ("1", "J4-HV inductive proximity sensor")],
        "fasteners": [("4", "M3 × 10 mm socket head cap bolt"), ("2", "M3 × 22 mm socket head cap bolt")],
        "parts_notes": [],
    },
    "HotJoe": {
        "slot": 4, "function": "CNC spindle for light engraving and milling",
        "about": "Spindle attachment with an ER8 collet and a 2814 1000 kV brushless motor, driven by an 80 A HobbyWing ESC on 24 V power.",
        "setup": "<code>CNC_JOB_SETUP FILE=&lt;name&gt;.gcode</code>", "outputs": "<code>Spindle_power</code> relay, <code>SPINDLE_SPEED</code> ESC signal",
        "pins": {3: "Thermistor", 4: "Thermistor", 11: "24 V relay power", 12: "24 V relay power", 13: "Probe", 14: "Probe", 15: "Probe",
                 18: "PWM"},
        "image": "tool_hotjoe", "image_notes": ["Shown without safety covers.", "Blow-air provided by the universal blow-air system."],
        "printed": [], "hardware": [("1", "ER8 collet")], "fasteners": [], "parts_notes": [],
    },
    "DragKnife": {
        "slot": 5, "function": "Drag-knife cutting (vinyl, cardstock, thin foam)",
        "about": "A drag-knife tool designed for Roland No. 9 and No. 10 blade holders.",
        "setup": "<code>DRAGKNIFE_JOB_SETUP FILE=&lt;name&gt;.gcode</code>", "outputs": "None (passive tool)",
        "pins": {3: "Thermistor", 4: "Thermistor", 13: "Probe", 14: "Probe", 15: "Probe"},
        "image": "dragknife_render", "image_notes": ["Rendered from the build files."],
        "printed": [], "hardware": [], "fasteners": [], "parts_notes": [],
    },
}
