"""The user-added tool registry.

    myrhino/custom_tools.json   source of truth (portal + CLI write it, nothing else should)
    myrhino/custom_tools.cfg    generated Klipper config the macros read - never edit by hand

`save` writes both together or neither: the generated text is parsed back and compared with the
registry before any file is touched, and the previous JSON is kept as a timestamped backup.
"""
import ast
import configparser
import json
import os
import shutil
import datetime

from . import sections
from .errors import Fail
from .presets import EPHEMERAL_FIELDS, PORTAL_ONLY_FIELDS, SAFE_TEXT, SCHEMA_VERSION, SECTION_FIELDS

KEEP_BACKUPS = 10
_HEADER = ("# GENERATED by the rhino package (scripts/rhino_toolgen.py / rhino_portal.py) - do not edit by hand.\n"
           "# Change tools with ADD_TOOLHEAD / EDIT_TOOLHEAD / REMOVE_TOOLHEAD or the web portal.\n"
           "# Source of truth: myrhino/custom_tools.json. printer.cfg always includes this file.\n")


def empty():
    return {"version": SCHEMA_VERSION, "tools": {}, "hardware": {}}


def load(paths):
    p = paths.registry_json
    if not os.path.exists(p):
        return empty()
    try:
        with open(p, encoding="utf-8") as f:
            reg = json.load(f)
        if not isinstance(reg, dict) or not isinstance(reg.get("tools", {}), dict):
            raise ValueError("top level must be an object with a 'tools' object")
    except (OSError, ValueError) as e:
        raise Fail(f"{p} is unreadable: {e}")
    reg.setdefault("version", SCHEMA_VERSION)
    reg.setdefault("tools", {})
    reg.setdefault("hardware", {})
    if not isinstance(reg["hardware"], dict):
        raise Fail(f"{p} is unreadable: 'hardware' must be an object")
    return reg


def by_slot(reg):
    return sorted(reg["tools"].items(), key=lambda kv: int(kv[1]["slot"]))


def klipper_view(tool):
    """The tool as Klipper sees it: no portal notes/images, no one-shot creation fields, and no
    controls/macros (those become their own sections)."""
    return {k: v for k, v in tool.items() if k not in PORTAL_ONLY_FIELDS + EPHEMERAL_FIELDS + SECTION_FIELDS}


def pins_in_use(reg):
    """{board pin: 'ToolName'} for pins the registry itself creates."""
    out = {}
    for n, t in reg["tools"].items():
        for k in ("new_pin", "new_enable_pin"):
            if t.get(k):
                out[t[k]] = n
        for o, p in t.get("new_switch_pins", {}).items():
            out[p] = f"{n} ({o})"
        for c in t.get("controls", []):
            out[c["pin"]] = f"{n} ({c['name']})"
    for n, hw in reg.get("hardware", {}).items():
        out[hw["pin"]] = f"system hardware {n}"
    return out


def owned_outputs(reg):
    """{output_pin name: {'pwm': bool, 'tool': name}} for output pins the registry creates."""
    out = {}
    for n, t in reg["tools"].items():
        if t.get("new_pin"):
            out[t["power_pin"]] = {"pwm": True, "tool": n}
        if t.get("new_enable_pin"):
            out[t["enable_pin"]] = {"pwm": False, "tool": n}
        for o in t.get("new_switch_pins", {}):
            out[o] = {"pwm": False, "tool": n}
    return out


def pyrepr(x):
    """repr() limited to what Klipper's ast.literal_eval of a macro variable accepts."""
    if isinstance(x, dict):
        return "{" + ", ".join(f"{pyrepr(k)}: {pyrepr(v)}" for k, v in x.items()) + "}"
    if isinstance(x, (list, tuple)):
        return "[" + ", ".join(pyrepr(i) for i in x) + "]"
    if isinstance(x, bool):
        return "True" if x else "False"
    if isinstance(x, (int, float)):
        return repr(x)
    if isinstance(x, str):
        if not SAFE_TEXT.match(x):
            raise Fail(f"refusing to write unsafe text {x!r}")
        return "'" + x + "'"
    raise Fail(f"cannot serialise {x!r}")


def render_cfg(reg):
    tools = by_slot(reg)
    mapping = {int(t["slot"]): n for n, t in tools}
    lines = [_HEADER + "[gcode_macro CUSTOM_TOOLS]",
             "description: Registry of user-added toolheads (generated)",
             "variable_tool_mapping: " + pyrepr(mapping)]
    if tools:
        lines.append("variable_toolheads: {")
        for i, (n, t) in enumerate(tools):
            lines.append("  " + pyrepr(n) + ": " + pyrepr(klipper_view(t)) + ("," if i < len(tools) - 1 else ""))
        lines.append("  }")
    else:
        lines.append("variable_toolheads: {}")
    lines += ["gcode:", "  M117 Custom tools loaded", ""]
    for n, t in tools:
        if t.get("new_pin"):
            lines += [f"[output_pin {t['power_pin']}]", f"# power output created for toolhead {n}",
                      f"pin: {t['new_pin']}", "pwm: True", "value: 0", "shutdown_value: 0",
                      f"cycle_time: {t.get('new_pin_cycle', 0.01)}", ""]
        if t.get("new_enable_pin"):
            lines += [f"[output_pin {t['enable_pin']}]", f"# enable output created for toolhead {n}",
                      f"pin: {t['new_enable_pin']}", "value: 0", "shutdown_value: 0", ""]
        for o, p in t.get("new_switch_pins", {}).items():
            lines += [f"[output_pin {o}]", f"# switch output created for toolhead {n} (on with the tool)",
                      f"pin: {p}", "value: 0", "shutdown_value: 0", ""]
        lines += sections.tool_lines(n, t)
    lines += sections.hardware_lines(reg)
    lines += sections.safe_off_lines(reg)
    return "\n".join(lines) + "\n"


def verify_roundtrip(reg, text):
    """Parse the generated text the way Klipper will and make sure nothing was lost."""
    cp = configparser.RawConfigParser(strict=False, inline_comment_prefixes=("#", ";"))
    cp.optionxform = str
    try:
        cp.read_string(text)
        sec = dict(cp.items("gcode_macro CUSTOM_TOOLS"))
        mapping = ast.literal_eval(sec["variable_tool_mapping"].strip())
        tools = ast.literal_eval(sec["variable_toolheads"].strip())
    except (configparser.Error, KeyError, ValueError, SyntaxError) as e:
        raise Fail(f"internal error: generated config does not parse ({e})")
    want = {n: klipper_view(t) for n, t in reg["tools"].items()}
    if tools != want or set(mapping.values()) != set(want):
        raise Fail("internal error: generated config does not round-trip")
    have = set(cp.sections())
    for n, t in reg["tools"].items():
        need = [sections.control_section(n, c)[0][1:-1] for c in t.get("controls", [])]
        need += [f"gcode_macro {m['name']}" for m in t.get("macros", [])]
        need += [f"gcode_macro {mn}" for c in t.get("controls", []) for mn, *_ in sections.control_macros(n, t["slot"], c)]
        missing = [x for x in need if x not in have]
        if missing:
            raise Fail(f"internal error: generated config lost {', '.join(missing)}")
    for n, hw in reg.get("hardware", {}).items():
        need = [sections.control_section(n, hw, owner="system hardware")[0][1:-1]]
        need += [f"gcode_macro {mn}" for mn, *_ in sections.control_macros("", None, hw)]
        missing = [x for x in need if x not in have]
        if missing:
            raise Fail(f"internal error: generated config lost {', '.join(missing)}")


def _atomic(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(text)
    os.replace(tmp, path)


def save(paths, reg):
    cfg_text = render_cfg(reg)
    verify_roundtrip(reg, cfg_text)
    json_text = json.dumps(reg, indent=2, sort_keys=True) + "\n"
    _backup(paths)
    _atomic(paths.registry_json, json_text)
    _atomic(paths.registry_cfg, cfg_text)


def _backup(paths):
    p = paths.registry_json
    if not os.path.exists(p):
        return
    d = os.path.join(os.path.dirname(p), "registry_backups")
    os.makedirs(d, exist_ok=True)
    shutil.copy2(p, os.path.join(d, datetime.datetime.now().strftime("custom_tools-%Y%m%d-%H%M%S-%f.json")))
    old = sorted(os.listdir(d))[:-KEEP_BACKUPS]
    for f in old:
        try:
            os.remove(os.path.join(d, f))
        except OSError:
            pass
